name = "TSCPDetector"
uuid = "28c78530-8bb7-4fc0-9b88-04e8b391d412"
authors = ["Mehdi Lotfi"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
