name: Docs

on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.11"

      - name: Cache Julia artifacts
        uses: actions/cache@v4
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-artifacts-${{ hashFiles('docs/Project.toml', 'docs/Manifest.toml') }}

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.instantiate()'

      - name: Run doctests
        run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using TSCPDetector
            DocMeta.setdocmeta!(TSCPDetector, :DocTestSetup, :(using TSCPDetector); recursive=true)
            doctest(TSCPDetector)'

      - name: Build and deploy documentation
        env:
          JULIA_PKG_SERVER: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs docs/make.jl
