name: Docs

on:
  push:
    branches:
      - main
    paths:
    tags: ["*"]
  pull_request:
    branches:
      - main
    paths:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"

      - name: Use Julia cache
        uses: julia-actions/cache@v2

      - name: Instantiate docs environment
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'

      - name: Run doctests
        run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using TSCPDetector
            DocMeta.setdocmeta!(TSCPDetector, :DocTestSetup, :(using TSCPDetector); recursive=true)
            doctest(TSCPDetector)'

      - name: Build and deploy docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JULIA_PKG_SERVER: ""
        run: julia --project=docs docs/make.jl
